# Generated by Django 3.2.6 on 2021-08-16 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0009_alter_blog_post_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=200)),
                ('mail', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('createt_at', models.DateTimeField(auto_now_add=True)),
                ('blog_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.blog_post')),
            ],
        ),
    ]
