# Generated by Django 3.2.6 on 2021-08-13 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_alter_blog_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog_post',
            name='updated_at',
            field=models.DateField(auto_now=True),
        ),
    ]
