# Generated by Django 3.2.6 on 2021-08-17 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0012_alter_blog_post_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog_post',
            name='title',
            field=models.CharField(max_length=40),
        ),
    ]
