# Generated by Django 3.2.6 on 2021-08-13 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0002_page_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='page',
            old_name='content',
            new_name='url',
        ),
    ]
